
name: Fetch and Process Data

on:
  schedule:
    - cron: '0 */2 * * *'  # 每2小时执行一次
  workflow_dispatch:     # 支持手动触发

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Fetch JSON
      run: |
        curl -o data_test.json https://test.milkywayidle.com/game_data/marketplace.json
        python process.py
        
    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Auto-update data" || echo "No changes"
        git push
